/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_adoublei_GallaryActivity */

#ifndef _Included_com_example_adoublei_GallaryActivity
#define _Included_com_example_adoublei_GallaryActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
